name: 'clash_royale'
version: '1.0.0'
config-version: 2

profile: 'clash_royale'

model-paths: ["models"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
test-paths: ["tests"]
snapshot-paths: ["snapshots"]
analysis-paths: ["analyses"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  clash_royale:
    +materialized: view
    staging:
      clashroyal:
        +schema: staging
        base:
          +materialized: table
          +schema: base
    marts:
      +materialized: table
      +schema: marts
